name: Submodule Updates

on: # Run this workflow whenever called
  repository_dispatch:
    types: [submodule-update]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update Submodules"
          git push
