name: Update Submodules

# Run daily at 6:30am (NZST)
on:
  schedule:
    - cron:  '30 17 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull --recurse-submodules
          git submodule update --remote
          git add .
          git commit -m "Updated Submodules"
          git push origin main
