name: Update Submodules

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: true
        default: 'Update submodules'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git submodule update --remote
          git add .
          git commit -m "Updated Submodules"
          git push origin main
